### ISSUE TITLE
Could you please show the learning curve before and after equipped the CRF-RNN?

### ISSUE THREAD

**Issue by glhfgg1024** [KleinYuan/train-crfasrnn#2]
Hi, thanks a lot for sharing your valuable experience on CRF-RNN! If convenient, could you please show the learning curve before and after when eauipped the CRF-RNN?

Is the loss decreasing as expected? Thanks!

**Comment by KleinYuan** [comment]
@glhfgg1024 TBH, didn't get very good results.
I think a good choice for now, maybe just try [mask-rcnn](https://github.com/facebookresearch/Detectron)

**Comment by glhfgg1024** [comment]
@KleinYuan thanks a lot for your kind reply and suggestion!

**Comment by KleinYuan** [comment]
@glhfgg1024 I'm gonna close this issue since this is not really an issue. You can reopen it later.
